pr = input("ведите слово")
print(pr[:4])
hp = input("ciovo")
print(hp[-2::-1])
lp = input("clovo2")
print(lp[-2],end="") 
print(lp[-1])
jo = input("чотный")
print(jo[1::2])
print(jo[::2])
text = input("text")
print(text[-3:])
